version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escuela_web
    volumes:
      - ./:/var/www/html
    ports:
      - "8090:80"
    depends_on:
      - db
    restart: always

 
  db:
    image: mariadb:10.5
    container_name: escuela_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: escuela
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: escuela_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8091:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
